# Default values for gpu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

platform:
  openshift: true

nfd:
  enabled: false

psp:
  enabled: false

daemonsets:
  priorityClassName: system-node-critical
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

validator:
  repository: quay.io/mgiessing
  image: gpu-operator-validator
  # If version is not specified, then default is to use chart.AppVersion
  #version: ""
  imagePullPolicy: Always
  imagePullSecrets: []
  env: []
  args: []
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}
  plugin:
    env:
      - name: WITH_WORKLOAD
        value: "true"

operator:
  repository: quay.io/mgiessing
  image: gpu-operator
  # If version is not specified, then default is to use chart.AppVersion
  #version: ""
  imagePullPolicy: Always 
  imagePullSecrets: []
  priorityClassName: system-node-critical
  defaultRuntime: crio
  runtimeClass: nvidia
  initContainer:
    image: cuda
    repository: nvcr.io/nvidia
    version: 11.4.2-base-ubi8
    imagePullPolicy: IfNotPresent 
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
  annotations:
    openshift.io/scc: restricted-readonly
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
  logging:
    timeEncoding: epoch
  resources:
    limits:
      cpu: 500m
      memory: 350Mi
    requests:
      cpu: 200m
      memory: 100Mi

mig:
  strategy: single

driver:
  enabled: true
  use_ocp_driver_toolkit: false
  repository: quay.io/mgiessing
  image: driver
  version: "470.82.01-kvm"
  imagePullPolicy: Always 
  imagePullSecrets: []
  rdma:
    enabled: false
    useHostMofed: false
  manager:
    image: k8s-driver-manager
    repository: quay.io/mgiessing
    version: v0.2.0-ubi8
    imagePullPolicy: Always 
    env:
      - name: ENABLE_AUTO_DRAIN
        value: "true"
      - name: DRAIN_USE_FORCE
        value: "false"
      - name: DRAIN_POD_SELECTOR_LABEL
        value: ""
      - name: DRAIN_TIMEOUT_SECONDS
        value: "0s"
      - name: DRAIN_DELETE_EMPTYDIR_DATA
        value: "false"
  env: []
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}
  # private mirror repository configuration
  repoConfig:
    configMapName: ""
  # custom ssl key/certificate configuration
  certConfig:
    name: ""
  # vGPU licensing configuration
  licensingConfig:
    configMapName: ""
    nlsEnabled: false
  # vGPU topology daemon configuration
  virtualTopology:
    config: ""

toolkit:
  enabled: true
  repository: quay.io/mgiessing
  image: container-toolkit
  version: 1.7.2-ubi8
  imagePullPolicy: Always
  imagePullSecrets: []
  env: []
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}

devicePlugin:
  repository: quay.io/mgiessing
  image: k8s-device-plugin
  version: v0.10.0-ubi8
  imagePullPolicy: Always 
  imagePullSecrets: []
  args: []
  env:
    - name: PASS_DEVICE_SPECS
      value: "true"
    - name: FAIL_ON_INIT_ERROR
      value: "true"
    - name: DEVICE_LIST_STRATEGY
      value: envvar
    - name: DEVICE_ID_STRATEGY
      value: uuid
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all
  securityContext:
    privileged: true
  resources: {}

dcgm:
  enabled: true
  repository: quay.io/mgiessing
  image: dcgm
  version: 2.3.1-ubi8
  imagePullPolicy: Always 
  hostPort: 5555
  args: []
  env: []
  securityContext: {}
  resources: {}

dcgmExporter:
  repository: quay.io/mgiessing
  image: dcgm-exporter
  version: 2.3.1-2.6.0-ubi8
  imagePullPolicy: Always 
  env:
    - name: DCGM_EXPORTER_LISTEN
      value: ":9400"
    - name: DCGM_EXPORTER_KUBERNETES
      value: "true"
    - name: DCGM_EXPORTER_COLLECTORS
      value: "/etc/dcgm-exporter/dcp-metrics-included.csv"
  securityContext: {}
  resources: {}

gfd:
  repository: quay.io/mgiessing
  image: gpu-feature-discovery
  version: v0.4.1
  imagePullPolicy: Always 
  imagePullSecrets: []
  env:
    - name: GFD_SLEEP_INTERVAL
      value: 60s
    - name: GFD_FAIL_ON_INIT_ERROR
      value: "true"
  podSecurityContext: {}
  securityContext: {}
  resources: {}


migManager:
  enabled: true
  repository: quay.io/mgiessing
  image: k8s-mig-manager
  version: v0.2.0-ubi8
  imagePullPolicy: Always 
  imagePullSecrets: []
  env:
    - name: WITH_REBOOT
      value: "false"
  securityContext:
    privileged: true
  resources: {}
  config:
    name: ""
  gpuClientsConfig:
    name: ""

nodeStatusExporter:
  enabled: false
  repository: quay.io/mgiessing
  image: gpu-operator-validator
  # If version is not specified, then default is to use chart.AppVersion
  #version: ""
  imagePullPolicy: Always 
  imagePullSecrets: []
  resources: {}

node-feature-discovery:
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"

    config: |
      sources:
        pci:
          deviceLabelFields:
          - vendor

  master:
    extraLabelNs:
      - nvidia.com

  serviceAccount:
    name: node-feature-discovery
